version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "8080:80"
      - "9145:9145"  # Prometheus metrics endpoint
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - LOG_LEVEL=info
    networks:
      - app_network
    volumes:
      - ./logs:/var/log/nginx
      - ./config:/etc/nginx/conf.d
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_network
    depends_on:
      - webapp

networks:
  app_network:
    driver: bridge 