global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing Nginx metrics endpoint
scrape_configs:
  - job_name: 'nginx'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['webapp:80']
    
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] 